# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
 matrix:
   windows:
     imageName: 'windows-latest'
     cmakeArgs: '-G "Visual Studio 17 2019 Win64"'
     buildSystem : 'CMAKE'
   linux:
     imageName: 'ubuntu-latest'
     cmakeArgs: ''
     buildSystem : 'CMAKE'
   android:
     imageName: 'windows-latest'
     buildSystem : 'JNI'

pool:
  vmImage: $(imageName)

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'choco install ninja'
  condition: eq( variables['Agent.JobName'], 'Job android' )

- task: CMake@1
  inputs:
    cmakeArgs: $(cmakeArgs)
  condition: eq( variables['buildSystem'], 'CMAKE' )

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'tree'