# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
 matrix:
   windows:
     imageName: 'windows-latest'
     cmakeArgs: '-G "Visual Studio 16 2019"'
     buildSystem : 'CMAKE'
   linux:
     imageName: 'ubuntu-latest'
     cmakeArgs: ''
     buildSystem : 'CMAKE'
   android:
     imageName: 'windows-latest'
     buildSystem : 'JNI'

pool:
  vmImage: $(imageName)

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'choco install ninja'
  condition: eq( variables['Agent.JobName'], 'Job android' )

- task: CMake@1
  inputs:
    workingDirectory: 'Native'
    cmakeArgs: 'CMakeLists.txt $(cmakeArgs)'
  condition: eq( variables['buildSystem'], 'CMAKE' )

- task: VSBuild@1
  inputs:
    solution: 'Native\mikktspace.sln'
    platform: 'x64'
    configuration: 'Release'
    msbuildArchitecture: 'x64'
  condition: eq( variables['Agent.JobName'], 'Job windows' )

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'tree /F /A'
    errorActionPreference: 'continue'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      make
      tree
  condition: eq( variables['Agent.OS'], 'Linux' )